[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"
description = "zero to production in rust"

[lib]
path = "src/lib.rs"

[[bin]]
name = "zero2prod"
path = "src/main.rs"

[dependencies]
actix-web = "4.9.0"

[dev-dependencies]
actix-rt = "2.10.0"
reqwest = "0.12.7"
